import '../models/alarm_data.dart';

class BmsAlarmCatalog {
  const BmsAlarmCatalog._();

  static List<AlarmData> samples({DateTime? timestamp}) {
    final time = timestamp ?? DateTime(2026, 5, 19, 10, 30);
    return [
      _alarm(
        code: 'CELL_OV',
        title: 'Sobretension de celda',
        category: AlarmCategory.voltage,
        severity: AlarmSeverity.critical,
        technical: 'Una celda ha superado el umbral maximo configurado.',
        user: 'Una celda tiene un voltaje demasiado alto.',
        action: 'Detenga la carga y revise el cargador o el balanceo.',
        timestamp: time,
      ),
      _alarm(
        code: 'CELL_UV',
        title: 'Subtension de celda',
        category: AlarmCategory.voltage,
        severity: AlarmSeverity.critical,
        technical: 'Una celda esta por debajo del umbral minimo configurado.',
        user: 'Una celda esta demasiado descargada.',
        action: 'Detenga la descarga y cargue la bateria con un cargador compatible.',
        timestamp: time,
      ),
      _alarm(
        code: 'PACK_OV',
        title: 'Sobretension del pack',
        category: AlarmCategory.voltage,
        severity: AlarmSeverity.critical,
        technical: 'El voltaje total del pack supera el limite del BMS.',
        user: 'La bateria tiene un voltaje total demasiado alto.',
        action: 'Detenga la carga y revise el cargador.',
        timestamp: time,
      ),
      _alarm(
        code: 'PACK_UV',
        title: 'Subtension del pack',
        category: AlarmCategory.voltage,
        severity: AlarmSeverity.critical,
        technical: 'El voltaje total del pack esta por debajo del limite seguro.',
        user: 'La bateria esta demasiado descargada.',
        action: 'Detenga el consumo y cargue la bateria cuanto antes.',
        timestamp: time,
      ),
      _alarm(
        code: 'CHG_OC',
        title: 'Sobrecorriente en carga',
        category: AlarmCategory.current,
        severity: AlarmSeverity.critical,
        technical: 'La corriente de carga supera el umbral permitido.',
        user: 'El cargador esta entregando demasiada corriente.',
        action: 'Desconecte el cargador y use uno compatible.',
        timestamp: time,
      ),
      _alarm(
        code: 'DSG_OC',
        title: 'Sobrecorriente en descarga',
        category: AlarmCategory.current,
        severity: AlarmSeverity.critical,
        technical: 'La corriente de descarga supera el umbral permitido.',
        user: 'El equipo conectado demanda demasiada corriente.',
        action: 'Reduzca la carga conectada y revise la instalacion.',
        timestamp: time,
      ),
      _alarm(
        code: 'SHORT',
        title: 'Cortocircuito',
        category: AlarmCategory.current,
        severity: AlarmSeverity.critical,
        technical: 'El BMS ha detectado una condicion de cortocircuito.',
        user: 'Se ha detectado un posible cortocircuito.',
        action: 'Desconecte el equipo y contacte con soporte tecnico.',
        timestamp: time,
      ),
      _alarm(
        code: 'CHG_OT',
        title: 'Alta temperatura en carga',
        category: AlarmCategory.temperature,
        severity: AlarmSeverity.critical,
        technical: 'Temperatura superior al limite permitido durante carga.',
        user: 'La bateria esta demasiado caliente para cargar.',
        action: 'Detenga la carga y espere a que baje la temperatura.',
        timestamp: time,
      ),
      _alarm(
        code: 'DSG_OT',
        title: 'Alta temperatura en descarga',
        category: AlarmCategory.temperature,
        severity: AlarmSeverity.critical,
        technical: 'Temperatura superior al limite permitido durante descarga.',
        user: 'La bateria esta demasiado caliente durante el uso.',
        action: 'Reduzca consumo, mejore ventilacion y espere enfriamiento.',
        timestamp: time,
      ),
      _alarm(
        code: 'CHG_UT',
        title: 'Carga bloqueada por baja temperatura',
        category: AlarmCategory.temperature,
        severity: AlarmSeverity.warning,
        technical: 'Carga bloqueada por temperatura inferior al umbral seguro.',
        user:
            'El BMS ha detenido la carga porque la bateria esta por debajo de la temperatura segura de carga.',
        action:
            'Espere a que la bateria alcance una temperatura adecuada antes de cargarla. No fuerce la carga en frio.',
        timestamp: time,
      ),
      _alarm(
        code: 'DSG_UT',
        title: 'Baja temperatura en descarga',
        category: AlarmCategory.temperature,
        severity: AlarmSeverity.warning,
        technical: 'Descarga limitada por temperatura inferior al umbral seguro.',
        user: 'La bateria esta demasiado fria para descargarse con normalidad.',
        action: 'Espere a que la bateria alcance una temperatura adecuada.',
        timestamp: time,
      ),
      _alarm(
        code: 'CELL_DIFF',
        title: 'Diferencia elevada entre celdas',
        category: AlarmCategory.balancing,
        severity: AlarmSeverity.warning,
        technical: 'Delta de voltaje entre celdas por encima del rango esperado.',
        user: 'Hay una diferencia elevada entre celdas.',
        action: 'Realice una carga completa y contacte con soporte si persiste.',
        timestamp: time,
      ),
      _alarm(
        code: 'TEMP_SENSOR',
        title: 'Fallo de sensor de temperatura',
        category: AlarmCategory.hardware,
        severity: AlarmSeverity.critical,
        technical: 'Lectura invalida o ausente en sensor de temperatura.',
        user: 'La bateria no puede leer correctamente una temperatura interna.',
        action: 'No fuerce la bateria y contacte con soporte tecnico.',
        timestamp: time,
      ),
      _alarm(
        code: 'COMM',
        title: 'Fallo de comunicacion',
        category: AlarmCategory.communication,
        severity: AlarmSeverity.warning,
        technical: 'Comunicacion BLE/BMS interrumpida o inconsistente.',
        user: 'La comunicacion con la bateria no es estable.',
        action: 'Acerque el movil a la bateria y vuelva a conectar.',
        timestamp: time,
      ),
      _alarm(
        code: 'CHG_MOS_OFF',
        title: 'MOSFET de carga desactivado',
        category: AlarmCategory.mosfet,
        severity: AlarmSeverity.warning,
        technical: 'El MOSFET de carga esta deshabilitado por el BMS.',
        user: 'La bateria no permite carga en este momento.',
        action: 'Revise alarmas activas, temperatura y cargador.',
        timestamp: time,
      ),
      _alarm(
        code: 'DSG_MOS_OFF',
        title: 'MOSFET de descarga desactivado',
        category: AlarmCategory.mosfet,
        severity: AlarmSeverity.warning,
        technical: 'El MOSFET de descarga esta deshabilitado por el BMS.',
        user: 'La bateria no permite descarga en este momento.',
        action: 'Revise protecciones y reduzca la carga conectada.',
        timestamp: time,
      ),
      _alarm(
        code: 'BMS_INTERNAL',
        title: 'Error interno BMS',
        category: AlarmCategory.hardware,
        severity: AlarmSeverity.critical,
        technical: 'El BMS informa de un error interno.',
        user: 'La electronica de proteccion ha detectado un error interno.',
        action: 'Detenga el uso y contacte con soporte INNPO.',
        timestamp: time,
      ),
      _alarm(
        code: 'UNKNOWN_PROTECTION',
        title: 'Proteccion activa desconocida',
        category: AlarmCategory.unknown,
        severity: AlarmSeverity.critical,
        technical: 'Codigo de proteccion no reconocido por la app.',
        user: 'La bateria ha activado una proteccion no identificada.',
        action: 'Genere un informe y contacte con soporte tecnico.',
        timestamp: time,
      ),
    ];
  }

  static AlarmData _alarm({
    required String code,
    required String title,
    required AlarmCategory category,
    required AlarmSeverity severity,
    required String technical,
    required String user,
    required String action,
    required DateTime timestamp,
  }) {
    return AlarmData(
      code: code,
      title: title,
      technicalDescription: technical,
      userFriendlyDescription: user,
      severity: severity,
      recommendedAction: action,
      timestamp: timestamp,
      isActive: false,
      category: category,
    );
  }
}

